### ISSUE TITLE
As a user, I want to go to the Sign up screen so I can register an account.

### ISSUE THREAD

**Issue by nicorod93** [nicorod93/Swap#1]
## Story/Task Details
- [x] Sign up button on login screen created and functionality implemented
- [x] Sign up screen implemented
- [x] User able to click on sign up button to take them to sign up screen

## Acceptance Scenarios
_User type: New student_
The following story assumes a user with the following properties:
1. High school student
2. Has not registered an account
3. Has an iOS device
4. The device is online

Scenario: A new user wants to register an account.
- Given: the user is on the Login screen;
- When: the user presses the Create Account button;
- Then: the user is taken to the Sign up screen.

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by dbarrundiag** [comment]
Could we generate an alert for the following errors:
1. The email address is already in use by another account.
2. The re-type password does not match the password
3. The password does not meet the requirements.

**Comment by dbarrundiag** [comment]
Alert errors generated.
