### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by apatronl** [nicorod93/Swap#12]
## Story/Task Details
- [x] Implement automatic login

## Acceptance Scenarios
_User type:_
The following stories assume a user with the following properties:
1. A user with an existing account who has previously logged in (and not logged out) on their device. 

Scenario: 
- Given: A user has logged in before
- When: the user opens the app
- Then: the user should be automatically logged in to his/her account.

----------------------------------------------------------------------------------------------------

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by dbarrundiag** [comment]
@apatronl @nicorod93  should we change this to be part of Sprint 1 milestone as we did it for Sprint 1?
