### ISSUE TITLE
As a user, I want to visit the "Frequently Asked Questions" (FAQ) screen so that I can see what issues are of relevance

### ISSUE THREAD

**Issue by taylorhavrilak** [nicorod93/Swap#15]
## Story/Task Details
- [x] Implement FAQ screen
- [x] Popular questions shown (statically)

## Acceptance Scenarios
_User type:_
The following stories assume a user with the following properties:
1. Is on the home screen of the application

Scenario: 
- Given: the user is on the home screen of the application
- When: the user taps on the "Frequently Asked Questions" button
- Then: the user should be on the Frequently Asked Questions (FAQ) screen and see popular questions from other users

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by dbarrundiag** [comment]
Proposed Architecture for this (v1):
```
{
  .
  .
  .
  'questions': {
      'q1': {
          'question': 'gffgfg',
          'answer': 'fdfdfdfd',
      }
      .
      .
      .

  }
}
```

**Comment by dbarrundiag** [comment]
re opening... must add FAQ to the DB

**Comment by dbarrundiag** [comment]
@apatronl UI changes before closing

**Comment by apatronl** [comment]
UI changes done.

**Comment by nicorod93** [comment]
Was incorrectly placed as a Sprint 1 item
