### ISSUE TITLE
As a user, I want to select a matched candidate to be my match.

### ISSUE THREAD

**Issue by nicorod93** [nicorod93/Swap#19]
## Story/Task Details
- [x] Create new database to store matches
- [x] Add button to allow user to select a candidate to be their match
- [x] Have recipient accept or deny the match request
- [x] Update matching algorithm

## Acceptance Scenarios
Scenario: 
- Given: the user is on a matched candidate's profile and has yet to receive a match
- When: the user presses the Match button
- Then: the recipient is sent an alert notifying them that a user has requested to match with them

Scenario: 
- Given: the user is on a matched candidate's profile and has already received a match
- When: the user presses the Match button
- Then: the user is present with an alert notifying them that they already have a match and cannot receive another match

Scenario: 
- Given: a user has yet to receive a match
- When: the user is presented with an alert notifying them that that another user has requested to match with them
- Then: the user has the option to accept or deny the request

Scenario: 
- Given: a user has yet to receive a match and is presented with an alert notifying them that that another user has requested to match with them
- When: the user selects the option to accept the request
- Then: the database is updated to add both users as matches and the user who requested the match is notified that the match was successful

Scenario: 
- Given: a user has yet to receive a match and is presented with an alert notifying them that that another user has requested to match with them
- When: the user selects the option to deny the request
- Then: the user who requested the match is notified that the match was not successful

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by dbarrundiag** [comment]
@nicorod93 In charge of the listener and send the notification to the target user.
@dbarrundiag In charge of changing database for potential users.

**Comment by dbarrundiag** [comment]
@nicorod93 In charge of the logic to ensure that if a user has a pending friend request or has a connection, it should not appear in the "Get a Match" queue.
