### ISSUE TITLE
As a user, I want to log in to my account so that I can access the application.

### ISSUE THREAD

**Issue by nicorod93** [nicorod93/Swap#3]
## Story/Task Details
- [x] Implement login screen
- [x] Implement login functionality

## Acceptance Scenarios
_User type: Student who is not logged in to their account_
The following stories assume a user with the following properties:
1. High school student
2. Desires to travel abroad and/or to host another high school student
3. Uses the app to fulfill this desire
4. Has an iOS device
5. The device is online
6. Is not logged into their account

Scenario: A user who has already registered and has completed the questionnaire logs in with a valid email and password.
- Given: the user has already created an account and is on the Login screen;
- When: they provide a valid email and password, and they press the Login button;
- Then: they are successfully logged in and are taken to the Home screen.

Scenario: A user who has already registered but has not completed the questionnaire logs in with a valid email and password.
- Given: the user has already created an account and is on the Login screen;
- When: they provide a valid email and password, and they press the Login button;
- Then: they are successfully logged in and are taken to the Questionnaire screen.

Scenario: A user who has already registered tries to log in with an invalid email.
- Given: the user has already created an account and is on the Login screen;
- When: they provide an invalid email, and they press the Login button;
- Then: they are presented with an error message and are kept on the Login screen.

Scenario: A user who has already registered tries to log in with a valid email but incorrect password.
- Given: the user has already created an account and is on the Login screen;
- When: they provide a valid email but incorrect password, and they press the Login button;
- Then: they are presented with an error message and are kept on the Login screen.

Scenario: A new user tries to log in.
- Given: the user has not already created an account and is on the Login screen;
- When: they provide an email that is not already in the database, they provide a valid password, and they press the Login button;
- Then: they are presented with an error message and are provided with a button to take them to the Registration screen.

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by apatronl** [comment]
This is done.

**Comment by dbarrundiag** [comment]
Could we generate an alert for the following errors:

The email address is not registered with this application.
The password does not match the password for this email.
