### ISSUE TITLE
As a user, I want to get a match so that I can start chatting with my match.

### ISSUE THREAD

**Issue by nicorod93** [nicorod93/Swap#5]
## Story/Task Details
- [x] Implement matching button
- [x] Implement version 1 of the matching algorithm
- [x] Displays list of all users with matching user types and corresponding country origin and destinations
- [x] User able to see each candidates profile
- [x] Display error message if a user has not filled out questionnaire

## Acceptance Scenarios
Scenario: A user who has yet to be matched wants to receive a match.
- Given: the user is on the Matching screen;
- When: the user presses Match button;
- Then: the user is taken to a new screen and presented with a list of possible matches.

Scenario: A user who has not filled out the questionnaire wants to receive a match.
- Given: the user is on the Matching screen;
- When: the user presses the Match button;
- Then: the user is presented with a message notifying them that they need to fill out the questionnaire.

Scenario: A user who has been provided with a list of candidates wants to see a matched users' profile.
- Given: the user is on the MatchedCandidates screen;
- When: the user selects a row that has a user;
- Then: the user is presented with the Profile screen of the selected user.

Scenario: A user who has selected the Get Match button wants to see a matched users' profile.
- Given: the user is on the MatchedCandidates screen;
- When: the user selects a row that does not have a user;
- Then: the user is not presented with a new screen and nothing happens.

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by dbarrundiag** [comment]
@nicorod93 what's missing to close this?

**Comment by nicorod93** [comment]
Needed to add back buttons, but it is done now
