### ISSUE TITLE
As a user, I want to fill out the questionnaire so that I can receive the best possible match.

### ISSUE THREAD

**Issue by nicorod93** [nicorod93/Swap#7]
## Story/Task Details
- [x] Implement Questionnaire screen
- [x] Update database with user's preferences

## Acceptance Scenarios
Scenario: A user fills in the Destination section.
- Given: the user is on the Questionnaire screen;
- When: they select the Destination option, and they select one of the available countries;
- Then: their account is updated to reflect the selected country as their Destination.

Scenario: A user fills in the Gender section.
- Given: the user is on the Questionnaire screen;
- When: they select the Gender option, and they select between Male or Female;
- Then: their account is updated to reflect their selected Gender.

Scenario: A user fills in the Siblings section.
- Given: the user is on the Questionnaire screen;
- When: they select the Siblings option, and they input the number of siblings;
- Then: their account is updated to reflect the amount of siblings specified.

Scenario: A user fills in the Activities section.
- Given: the student is on the Questionnaire screen;
- When: they select the Activities option, and they select one or more activities;
- Then: their account is updated to reflect the selected activities.

Scenario: A user fills in the Country of Origin section.
- Given: the student is on the Questionnaire screen;
- When: they select the Country of Origin option, and they select their country;
- Then: their account is updated to reflect the selected country as their country of origin.

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by dbarrundiag** [comment]
@taylorhavrilak once Activities is done, ping me so I can work on saving data to DB

**Comment by dbarrundiag** [comment]
@taylorhavrilak bug fix. As a user I click for the first time to checkmark a few activities and then click Done. The user wants to add or edit the activities, so they click again, all the previous checkmarks will be lost.
