### ISSUE TITLE
As a user, I want to edit my profile so that my account contains the most updated information

### ISSUE THREAD

**Issue by nicorod93** [nicorod93/Swap#8]
## Story/Task Details
- [x] Add functionality to edit profile (first name, last name, date of birth)
- [x] Add functionality to edit profile picture
- [x] Add functionality to edit questionnaire responses
- [x] Update profile view immediately after changes are saved

## Acceptance Scenarios
Scenario: A user who is currently selected as a traveler wants to edit their Profile to become a host.
- Given: the user is on the Profile screen;
- When: they select the Host option as the user type;
- Then: their account is updated to reflect that they are now a host.

Scenario: A user who is currently selected as a traveler wants to edit their Profile to become a host and a traveler.
- Given: the user is on the Profile screen;
- When: they select the Both option as the user type;
- Then: their account is updated to reflect that they are now a host and a traveler.

Scenario: A user who is currently selected as a host wants to edit their Profile to become a traveler.
- Given: the user is on the Profile screen;
- When: they select the Traveler option as the user type;
- Then: their account is updated to reflect that they are now a traveler.

Scenario: A user who is currently selected as a host wants to edit their Profile to become a host and a traveler.
- Given: the user is on the Profile screen;
- When: they select the Both option as the user type;
- Then: their account is updated to reflect that they are now a host and a traveler.

Scenario: A user who is currently selected as a host and a traveler wants to edit their Profile to only become a traveler.
- Given: the user is on the Profile screen;
- When: they select the Traveler option as the user type;
- Then: their account is updated to reflect that they are now a traveler.

Scenario: A user who is currently selected as a host and a traveler wants to edit their Profile to only become a host.
- Given: the user is on the Profile screen;
- When: they select the Host option as the user type;
- Then: their account is updated to reflect that they are now a host.

## Done Done Criteria
- It passes all Acceptance Scenarios.
- UI changes has been approved by Ale.
- Swift design guideliness have been approved by Ale.
- DB changes has been approved by Daniel.
- Code is merged to 'master' branch.

**Comment by dbarrundiag** [comment]
@apatronl Questionnaire data is now in the database. Blocker removed, now you can read questionnaire data from firebase. 😃
